// ============================================
// BASE DE DONNÉES DE 200 QUESTIONS
// Structure: {q: question, o: [options], c: correct_index}
// ============================================

const questionsDB = [
    // SECTION 1: Définitions de base (30 questions)
    {q: "Qu'est-ce qu'un groupe selon la psychosociologie ?", o: ["Un ensemble de personnes partageant un objectif commun", "Des personnes qui travaillent dans le même bureau", "Un nombre quelconque de personnes", "Des personnes du même âge"], c: 0},
    {q: "Quel est l'élément essentiel d'un groupe ?", o: ["L'interaction entre les membres", "Le même salaire", "La même nationalité", "Le même diplôme"], c: 0},
    {q: "Qu'est-ce que la dynamique de groupe ?", o: ["L'étude des interactions humaines dans les groupes", "La vitesse de travail du groupe", "Le nombre de membres", "L'ancienneté du groupe"], c: 0},
    {q: "Qui est le fondateur de la théorie de la dynamique de groupe ?", o: ["Kurt Lewin", "Sigmund Freud", "Carl Jung", "Abraham Maslow"], c: 0},
    {q: "Combien d'étapes propose Bruce Tuckman dans son modèle ?", o: ["5 étapes", "3 étapes", "7 étapes", "4 étapes"], c: 0},
    {q: "Quelle est la première étape du modèle de Tuckman ?", o: ["Formation", "Turbulence", "Performance", "Normalisation"], c: 0},
    {q: "Que signifie 'psychosociologie' ?", o: ["L'étude des comportements humains en groupe", "L'étude de la psychologie animale", "L'étude des maladies mentales", "L'étude de la société"], c: 0},
    {q: "Qu'est-ce que l'identité collective ?", o: ["Le sentiment d'appartenance au groupe", "Le nom du groupe", "Le logo de l'entreprise", "L'adresse du bureau"], c: 0},
    {q: "Quelle est l'importance de la dynamique de groupe ?", o: ["Elle influence la performance des équipes", "Elle détermine les salaires", "Elle fixe les horaires", "Elle choisit les vacances"], c: 0},
    {q: "Que favorise une bonne dynamique de groupe ?", o: ["La motivation et la cohésion", "La compétition destructrice", "L'isolement", "La confusion"], c: 0},
    {q: "Comment se définit un groupe ?", o: ["Personnes en interaction avec objectif commun", "Personnes dans un même lieu", "Personnes du même âge", "Personnes de même profession"], c: 0},
    {q: "La dynamique de groupe étudie quoi ?", o: ["Les processus d'interaction et d'influence", "Les salaires", "Les horaires", "Les vacances"], c: 0},
    {q: "Pourquoi la dynamique est importante en entreprise ?", o: ["Elle améliore la performance collective", "Elle réduit les salaires", "Elle augmente les horaires", "Elle impose des règles"], c: 0},
    {q: "Qu'est-ce qu'un objectif commun ?", o: ["Un but partagé par tous les membres", "Un objectif individuel", "Une obligation", "Une contrainte"], c: 0},
    {q: "L'identité collective favorise quoi ?", o: ["Le sentiment d'appartenance", "La division", "Le conflit", "L'isolement"], c: 0},
    {q: "Les interactions de groupe sont ?", o: ["Essentielles au fonctionnement", "Optionnelles", "Inutiles", "Dangereuses"], c: 0},
    {q: "La psychosociologie combine quoi ?", o: ["Psychologie et sociologie", "Médecine et droit", "Économie et politique", "Art et sport"], c: 0},
    {q: "Qu'étudie la psychosociologie organisationnelle ?", o: ["Le comportement humain en organisation", "Les machines", "Les bâtiments", "Les finances"], c: 0},
    {q: "Un groupe efficace a besoin de ?", o: ["Communication et cohésion", "Silence et division", "Conflit permanent", "Isolement"], c: 0},
    {q: "La taille idéale d'un groupe est ?", o: ["Variable selon les objectifs", "Toujours 10 personnes", "Toujours 2 personnes", "Toujours 100 personnes"], c: 0},
    {q: "Les rôles dans un groupe sont ?", o: ["Complémentaires et nécessaires", "Identiques pour tous", "Inutiles", "Source de conflits"], c: 0},
    {q: "Un groupe mature se caractérise par ?", o: ["Autonomie et performance", "Dépendance totale", "Conflits constants", "Absence de règles"], c: 0},
    {q: "La cohésion de groupe dépend de ?", o: ["La qualité des relations", "Le nombre de membres", "La taille du bureau", "Les salaires"], c: 0},
    {q: "Un objectif clair permet ?", o: ["De mobiliser les énergies", "De créer la confusion", "D'augmenter les conflits", "De diviser"], c: 0},
    {q: "L'appartenance au groupe crée ?", o: ["Un sentiment de sécurité", "De l'anxiété", "Du rejet", "De l'indifférence"], c: 0},
    {q: "Les normes de groupe régulent ?", o: ["Les comportements des membres", "Seulement les horaires", "Rien du tout", "Les émotions négatives"], c: 0},
    {q: "Un groupe performant nécessite ?", o: ["Coordination et collaboration", "Compétition interne", "Individualisme", "Absence de règles"], c: 0},
    {q: "La diversité dans un groupe apporte ?", o: ["Richesse de perspectives", "Seulement des conflits", "De la confusion", "De l'inefficacité"], c: 0},
    {q: "Les interactions fréquentes favorisent ?", o: ["Le développement de liens", "L'isolement", "Les malentendus", "Le rejet"], c: 0},
    {q: "Un groupe sans objectif devient ?", o: ["Inefficace et démotivé", "Plus performant", "Plus créatif", "Plus uni"], c: 0},

    // SECTION 2: Kurt Lewin (20 questions)
    {q: "Quelle théorie Kurt Lewin a-t-il développée ?", o: ["La théorie du champ de forces", "La théorie de l'évolution", "La théorie de la relativité", "La théorie des cordes"], c: 0},
    {q: "Selon Lewin, le comportement dépend de quoi ?", o: ["La personne et son environnement", "Seulement la personnalité", "Seulement les gènes", "Le hasard"], c: 0},
    {q: "Quelle est la formule de Lewin ?", o: ["C = f(P,E)", "E = mc²", "F = ma", "V = d/t"], c: 0},
    {q: "Que représente 'P' dans la formule de Lewin ?", o: ["La personne", "Le projet", "Le profit", "La planète"], c: 0},
    {q: "Que représente 'E' dans la formule de Lewin ?", o: ["L'environnement", "L'énergie", "L'entreprise", "L'éducation"], c: 0},
    {q: "Quelle approche Lewin a-t-il privilégiée ?", o: ["L'approche interactionniste", "L'approche individualiste", "L'approche génétique", "L'approche behavioriste pure"], c: 0},
    {q: "Lewin est considéré comme le père de quoi ?", o: ["La psychologie sociale moderne", "La psychanalyse", "La psychiatrie", "La neurologie"], c: 0},
    {q: "Quel type de recherche Lewin a-t-il promu ?", o: ["La recherche-action", "La recherche pure", "La recherche médicale", "La recherche spatiale"], c: 0},
    {q: "Selon Lewin, qu'est-ce qui influence le comportement de groupe ?", o: ["Les forces du champ social", "Uniquement les individus", "Le hasard", "Les astres"], c: 0},
    {q: "Quelle était la nationalité d'origine de Kurt Lewin ?", o: ["Allemand", "Américain", "Français", "Anglais"], c: 0},
    {q: "Lewin a étudié principalement ?", o: ["La dynamique de groupe", "Les maladies mentales", "L'anatomie", "La physique"], c: 0},
    {q: "Le champ de forces représente ?", o: ["L'ensemble des influences sur le comportement", "Les forces physiques", "Les forces militaires", "Les forces de vente"], c: 0},
    {q: "Lewin a démontré l'importance de ?", o: ["L'environnement social", "Seulement la génétique", "Seulement la personnalité", "Le hasard"], c: 0},
    {q: "La recherche-action vise à ?", o: ["Résoudre des problèmes concrets", "Rester théorique", "Éviter la pratique", "Observer sans agir"], c: 0},
    {q: "Lewin a travaillé sur ?", o: ["Les styles de leadership", "La médecine", "L'architecture", "La cuisine"], c: 0},
    {q: "Selon Lewin, changer un comportement nécessite ?", o: ["Modifier l'environnement social", "Seulement la volonté", "Des médicaments", "Rien"], c: 0},
    {q: "Le concept de 'champ psychologique' désigne ?", o: ["L'espace de vie de la personne", "Un terrain de sport", "Un champ agricole", "Un champ magnétique"], c: 0},
    {q: "Lewin a émigré où ?", o: ["Aux États-Unis", "En France", "En Chine", "Au Japon"], c: 0},
    {q: "L'approche de Lewin est ?", o: ["Scientifique et pratique", "Uniquement théorique", "Mystique", "Artistique"], c: 0},
    {q: "Lewin a influencé ?", o: ["La psychologie sociale moderne", "Seulement la physique", "L'astrologie", "La gastronomie"], c: 0},

    // SECTION 3: Modèle de Tuckman (30 questions)
    {q: "Quelle est la 2ème étape du modèle de Tuckman ?", o: ["Turbulence (Storming)", "Formation", "Performance", "Dissolution"], c: 0},
    {q: "Quelle est la 3ème étape du modèle de Tuckman ?", o: ["Normalisation (Norming)", "Turbulence", "Formation", "Performance"], c: 0},
    {q: "Quelle est la 4ème étape du modèle de Tuckman ?", o: ["Performance (Performing)", "Formation", "Turbulence", "Dissolution"], c: 0},
    {q: "Quelle est la dernière étape du modèle de Tuckman ?", o: ["Dissolution (Adjourning)", "Performance", "Formation", "Turbulence"], c: 0},
    {q: "Que se passe-t-il durant l'étape de formation ?", o: ["Les membres apprennent à se connaître", "Les conflits éclatent", "Le groupe se dissout", "La performance est maximale"], c: 0},
    {q: "Que caractérise l'étape de turbulence ?", o: ["Les conflits et désaccords", "L'harmonie totale", "La dissolution", "La formation"], c: 0},
    {q: "Que se passe-t-il durant la normalisation ?", o: ["Établissement de règles et normes", "Dissolution du groupe", "Conflits intenses", "Première rencontre"], c: 0},
    {q: "Durant quelle étape le groupe est-il le plus efficace ?", o: ["Performance", "Formation", "Turbulence", "Dissolution"], c: 0},
    {q: "Pourquoi l'étape de dissolution existe-t-elle ?", o: ["Car les projets ont une fin", "Car les groupes échouent", "Par obligation légale", "Sans raison particulière"], c: 0},
    {q: "L'étape de turbulence est-elle nécessaire ?", o: ["Oui, elle permet la clarification", "Non, elle doit être évitée", "Elle est toujours négative", "Elle n'existe pas vraiment"], c: 0},
    {q: "Combien de temps dure chaque étape de Tuckman ?", o: ["Cela varie selon les groupes", "Exactement 1 mois", "1 semaine", "1 an"], c: 0},
    {q: "Peut-on sauter des étapes dans le modèle de Tuckman ?", o: ["Non, toutes les étapes sont importantes", "Oui, on peut passer directement à la performance", "Seulement la turbulence", "Oui, toutes sauf la formation"], c: 0},
    {q: "Que faire durant l'étape de turbulence ?", o: ["Faciliter la communication et résoudre les conflits", "Ignorer les problèmes", "Dissoudre le groupe", "Remplacer tous les membres"], c: 0},
    {q: "Quel est l'objectif de la normalisation ?", o: ["Créer une cohésion et des règles communes", "Augmenter les conflits", "Terminer le projet", "Recruter de nouveaux membres"], c: 0},
    {q: "Durant quelle étape la confiance s'établit-elle ?", o: ["Normalisation", "Formation", "Turbulence", "Dissolution"], c: 0},
    {q: "Que doit faire un leader durant la formation ?", o: ["Guider et structurer le groupe", "S'absenter", "Créer des conflits", "Dissoudre le groupe"], c: 0},
    {q: "La performance peut-elle baisser après avoir été atteinte ?", o: ["Oui, si de nouveaux conflits surgissent", "Non, elle est permanente", "Jamais", "Seulement le lundi"], c: 0},
    {q: "Quel sentiment domine durant la dissolution ?", o: ["Nostalgie et accomplissement", "Colère", "Confusion", "Indifférence totale"], c: 0},
    {q: "Un groupe peut-il rester à l'étape de turbulence ?", o: ["Oui, si les conflits ne sont pas résolus", "Non, c'est impossible", "Seulement 1 jour", "Jamais"], c: 0},
    {q: "Quelle étape nécessite le plus d'intervention du leader ?", o: ["Turbulence", "Performance", "Dissolution", "Normalisation"], c: 0},
    {q: "Durant la formation, les membres sont ?", o: ["Polis mais distants", "Très confiants", "En conflit", "Très performants"], c: 0},
    {q: "La turbulence est marquée par ?", o: ["L'émergence de conflits", "L'harmonie totale", "La performance maximale", "La dissolution"], c: 0},
    {q: "En normalisation, le groupe développe ?", o: ["Des normes et des règles", "Plus de conflits", "De l'individualisme", "De la méfiance"], c: 0},
    {q: "En performance, le groupe est ?", o: ["Autonome et efficace", "Dépendant du leader", "En conflit", "Désorganisé"], c: 0},
    {q: "La dissolution peut être ?", o: ["Planifiée ou imprévue", "Toujours négative", "Toujours positive", "Impossible"], c: 0},
    {q: "Un nouveau membre peut ramener le groupe à ?", o: ["Une étape antérieure", "La dissolution", "Aucune étape", "La performance uniquement"], c: 0},
    {q: "Le modèle de Tuckman est ?", o: ["Séquentiel mais flexible", "Rigide et fixe", "Inutile", "Impossible à appliquer"], c: 0},
    {q: "Reconnaître l'étape du groupe permet ?", o: ["D'adapter le leadership", "De dissoudre le groupe", "D'ignorer les problèmes", "De créer des conflits"], c: 0},
    {q: "La formation est caractérisée par ?", o: ["L'incertitude et la découverte", "La certitude absolue", "Les conflits intenses", "La performance"], c: 0},
    {q: "Le passage de la turbulence à la normalisation nécessite ?", o: ["Résolution des conflits", "Ignorer les problèmes", "Changer tous les membres", "Dissoudre le groupe"], c: 0},

    // SECTION 4: Facteurs influençant la dynamique (30 questions)
    {q: "Quel facteur influence la dynamique de groupe ?", o: ["Le style de leadership", "La couleur des murs", "Le jour de la semaine", "La météo"], c: 0},
    {q: "Qu'est-ce que la cohésion de groupe ?", o: ["Le degré d'unité et de solidarité", "Le nombre de membres", "L'âge moyen", "Le salaire moyen"], c: 0},
    {q: "Pourquoi la communication est-elle importante ?", o: ["Elle facilite la coordination et réduit les malentendus", "Elle fait perdre du temps", "Elle crée des conflits", "Elle n'est pas importante"], c: 0},
    {q: "Qu'est-ce que le conformisme social ?", o: ["La tendance à adopter les normes du groupe", "La rébellion constante", "L'individualisme extrême", "L'absence de règles"], c: 0},
    {q: "Quel style de leadership favorise la participation ?", o: ["Le leadership démocratique", "Le leadership autoritaire", "Le leadership absent", "Le leadership chaotique"], c: 0},
    {q: "Qu'est-ce qu'un leadership autoritaire ?", o: ["Un leader qui prend toutes les décisions seul", "Un leader absent", "Un leader qui consulte toujours", "Un leader sans pouvoir"], c: 0},
    {q: "Quel est l'avantage du leadership démocratique ?", o: ["Meilleure motivation et créativité", "Décisions plus rapides", "Moins de responsabilités", "Confusion totale"], c: 0},
    {q: "Que provoque un manque de communication ?", o: ["Malentendus et conflits", "Meilleure efficacité", "Plus de créativité", "Rien du tout"], c: 0},
    {q: "Comment renforcer la cohésion ?", o: ["Par des objectifs communs et la confiance", "Par la compétition interne", "Par l'isolement", "Par l'autoritarisme"], c: 0},
    {q: "Quel est le risque du conformisme excessif ?", o: ["La pensée de groupe et manque de créativité", "Trop d'innovation", "Trop de conflits", "Meilleure performance"], c: 0},
    {q: "Qu'est-ce que la pensée de groupe ?", o: ["Consensus sans analyse critique", "Débat constructif", "Diversité d'opinions", "Analyse approfondie"], c: 0},
    {q: "Comment encourager la participation ?", o: ["En valorisant toutes les contributions", "En critiquant les idées", "En imposant le silence", "En ignorant certains membres"], c: 0},
    {q: "Quel rôle joue la confiance dans un groupe ?", o: ["Elle favorise la collaboration et l'ouverture", "Elle crée des conflits", "Elle ralentit le travail", "Elle n'a pas d'importance"], c: 0},
    {q: "Comment établir la confiance ?", o: ["Par la transparence et le respect", "Par le secret", "Par la méfiance", "Par l'autoritarisme"], c: 0},
    {q: "Qu'est-ce qu'une norme de groupe ?", o: ["Une règle acceptée par tous les membres", "Une loi nationale", "Une suggestion", "Une obligation légale"], c: 0},
    {q: "Pourquoi les normes sont-elles importantes ?", o: ["Elles structurent les comportements", "Elles créent la confusion", "Elles sont inutiles", "Elles limitent la créativité"], c: 0},
    {q: "Comment un leader peut-il gérer les conflits ?", o: ["Par l'écoute et la médiation", "En les ignorant", "En prenant parti", "En excluant des membres"], c: 0},
    {q: "Quel est l'impact d'un mauvais leadership ?", o: ["Démotivation et conflits", "Meilleure performance", "Plus de créativité", "Aucun impact"], c: 0},
    {q: "Qu'est-ce que le leadership situationnel ?", o: ["Adapter son style à la situation", "Rester rigide", "Être toujours autoritaire", "Être toujours démocratique"], c: 0},
    {q: "Comment mesurer la cohésion d'un groupe ?", o: ["Par l'engagement et l'entraide", "Par le nombre de membres", "Par le budget", "Par la taille du bureau"], c: 0},
    {q: "Un leader efficace doit ?", o: ["S'adapter aux besoins du groupe", "Rester rigide", "Dominer totalement", "S'absenter"], c: 0},
    {q: "La communication non-verbale représente ?", o: ["Une part importante du message", "Rien du tout", "Seulement 5%", "Est inutile"], c: 0},
    {q: "L'écoute active consiste à ?", o: ["Comprendre vraiment l'autre", "Attendre son tour de parler", "Ignorer l'autre", "Couper la parole"], c: 0},
    {q: "Les feedbacks réguliers permettent ?", o: ["L'amélioration continue", "La démotivation", "Les conflits", "La confusion"], c: 0},
    {q: "Un climat de confiance favorise ?", o: ["L'expression libre des idées", "La censure", "La peur", "Le silence"], c: 0},
    {q: "La diversité des compétences ?", o: ["Enrichit le groupe", "Crée seulement des problèmes", "Est inutile", "Divise le groupe"], c: 0},
    {q: "Les rôles dans un groupe doivent être ?", o: ["Clairement définis", "Ambigus", "Inexistants", "Imposés"], c: 0},
    {q: "La motivation intrinsèque vient ?", o: ["De l'intérieur de la personne", "Des récompenses uniquement", "De la peur", "Des menaces"], c: 0},
    {q: "Un objectif SMART est ?", o: ["Spécifique, Mesurable, Atteignable, Réaliste, Temporel", "Vague et général", "Impossible", "Inutile"], c: 0},
    {q: "Le feedback constructif doit être ?", o: ["Spécifique et bienveillant", "Vague et critique", "Méchant", "Inexistant"], c: 0},

    // SECTION 5: Les conflits (40 questions)
    {q: "Les conflits sont-ils inévitables ?", o: ["Oui, dans toute organisation", "Non, jamais", "Seulement dans les grandes entreprises", "Seulement en hiver"], c: 0},
    {q: "Quelle est une cause fréquente de conflit ?", o: ["Mauvaise communication", "Bonne entente", "Objectifs clairs", "Ressources abondantes"], c: 0},
    {q: "Qu'est-ce qu'un conflit intra-individuel ?", o: ["Un conflit interne à une personne", "Entre deux personnes", "Entre deux groupes", "Entre deux entreprises"], c: 0},
    {q: "Qu'est-ce qu'un conflit interpersonnel ?", o: ["Entre deux ou plusieurs personnes", "À l'intérieur d'une personne", "Entre deux groupes", "Entre pays"], c: 0},
    {q: "Qu'est-ce qu'un conflit intragroupe ?", o: ["Au sein d'un même groupe", "Entre deux groupes", "Entre personnes de groupes différents", "International"], c: 0},
    {q: "Qu'est-ce qu'un conflit intergroupe ?", o: ["Entre deux groupes différents", "Au sein d'un groupe", "Dans une personne", "Entre deux personnes"], c: 0},
    {q: "Quelle cause peut provoquer un conflit ?", o: ["Répartition inéquitable des ressources", "Ressources abondantes", "Communication parfaite", "Objectifs identiques"], c: 0},
    {q: "Les différences de valeurs peuvent-elles causer des conflits ?", o: ["Oui, absolument", "Non, jamais", "Seulement dans certains pays", "Seulement entre générations"], c: 0},
    {q: "Un conflit peut-il être positif ?", o: ["Oui, s'il est bien géré", "Non, toujours négatif", "Jamais", "Impossible"], c: 0},
    {q: "Qu'apporte un conflit bien géré ?", o: ["Innovation et amélioration", "Destruction", "Démotivation", "Chaos"], c: 0},
    {q: "Que provoque un conflit mal géré ?", o: ["Stress et absentéisme", "Meilleure ambiance", "Plus de motivation", "Rien"], c: 0},
    {q: "Comment prévenir les conflits ?", o: ["Par une communication claire", "Par le silence", "Par l'évitement", "Par l'ignorance"], c: 0},
    {q: "Quel est le rôle de l'écoute active ?", o: ["Comprendre les besoins de chacun", "Ignorer les autres", "Imposer son opinion", "Créer des malentendus"], c: 0},
    {q: "La médiation est-elle utile dans les conflits ?", o: ["Oui, elle facilite la résolution", "Non, elle aggrave les choses", "Jamais", "Seulement dans les tribunaux"], c: 0},
    {q: "Qu'est-ce que l'escalade d'un conflit ?", o: ["L'intensification progressive", "La résolution rapide", "La disparition", "La stagnation"], c: 0},
    {q: "Comment éviter l'escalade ?", o: ["Intervenir tôt et communiquer", "Ignorer le problème", "Attendre que ça passe", "Créer plus de tensions"], c: 0},
    {q: "Les émotions jouent-elles un rôle dans les conflits ?", o: ["Oui, un rôle majeur", "Non, aucun", "Seulement chez certaines personnes", "Jamais"], c: 0},
    {q: "Comment gérer les émotions en conflit ?", o: ["Par la régulation émotionnelle et l'empathie", "Par la colère", "Par l'agressivité", "Par l'indifférence"], c: 0},
    {q: "Qu'est-ce que l'assertivité ?", o: ["Exprimer ses besoins en respectant autrui", "L'agressivité", "La passivité", "La manipulation"], c: 0},
    {q: "L'assertivité aide-t-elle à gérer les conflits ?", o: ["Oui, elle favorise le dialogue", "Non, elle aggrave tout", "Jamais", "Seulement parfois"], c: 0},
    {q: "Un conflit résolu renforce ?", o: ["La confiance et la cohésion", "Les tensions", "Les divisions", "La méfiance"], c: 0},
    {q: "Ignorer un conflit peut ?", o: ["L'aggraver avec le temps", "Le résoudre", "N'avoir aucun effet", "Toujours fonctionner"], c: 0},
    {q: "La négociation nécessite ?", o: ["Écoute et flexibilité", "Rigidité", "Domination", "Silence"], c: 0},
    {q: "Un médiateur doit être ?", o: ["Neutre et impartial", "Partial", "Autoritaire", "Absent"], c: 0},
    {q: "Les conflits de valeurs sont ?", o: ["Difficiles à résoudre", "Faciles à résoudre", "Inexistants", "Toujours résolus"], c: 0},
    {q: "L'empathie permet ?", o: ["De comprendre le point de vue de l'autre", "D'ignorer l'autre", "De dominer", "De manipuler"], c: 0},
    {q: "Un conflit constructif ?", o: ["Améliore les relations", "Détruit tout", "Est impossible", "N'existe pas"], c: 0},
    {q: "La frustration peut mener à ?", o: ["Des conflits si non exprimée", "Rien", "Du bonheur", "De la performance"], c: 0},
    {q: "Clarifier les attentes permet ?", o: ["De prévenir les malentendus", "De créer des conflits", "De compliquer", "Rien"], c: 0},
    {q: "Les conflits de rôles naissent ?", o: ["D'attentes contradictoires", "De clarté totale", "De bonne organisation", "De la perfection"], c: 0},
    {q: "Un dialogue ouvert favorise ?", o: ["La résolution des tensions", "Plus de conflits", "La confusion", "Le silence"], c: 0},
    {q: "La colère doit être ?", o: ["Exprimée de manière constructive", "Refoulée toujours", "Explosée violemment", "Ignorée"], c: 0},
    {q: "Un conflit latent est ?", o: ["Non exprimé mais présent", "Résolu", "Inexistant", "Toujours visible"], c: 0},
    {q: "La confrontation peut être ?", o: ["Constructive si respectueuse", "Toujours négative", "Inutile", "Dangereuse"], c: 0},
    {q: "Les stéréotypes peuvent ?", o: ["Créer des préjugés et conflits", "Améliorer les relations", "N'avoir aucun effet", "Résoudre les problèmes"], c: 0},
    {q: "Un compromis implique ?", o: ["Des concessions mutuelles", "La victoire totale", "La défaite totale", "Aucun changement"], c: 0},
    {q: "La gestion proactive des conflits ?", o: ["Prévient l'escalade", "Crée plus de problèmes", "Est inutile", "Est impossible"], c: 0},
    {q: "Les conflits révèlent parfois ?", o: ["Des problèmes organisationnels", "Rien d'utile", "Seulement du négatif", "La perfection"], c: 0},
    {q: "Un désaccord n'est pas nécessairement ?", o: ["Un conflit destructeur", "Toujours un conflit", "Positif", "Utile"], c: 0},
    {q: "La communication non-violente aide à ?", o: ["Exprimer ses besoins sans agresser", "Attaquer l'autre", "Éviter tout dialogue", "Manipuler"], c: 0},

    // SECTION 6: Thomas et Kilmann (20 questions)
    {q: "Combien de styles de gestion de conflits Thomas et Kilmann proposent-ils ?", o: ["5 styles", "3 styles", "7 styles", "10 styles"], c: 0},
    {q: "Quel est le premier style de Thomas-Kilmann ?", o: ["Compétition", "Évitement", "Collaboration", "Compromis"], c: 0},
    {q: "Qu'est-ce que le style compétition ?", o: ["Imposer sa solution, gagner à tout prix", "Éviter le conflit", "Chercher un accord mutuel", "Céder aux autres"], c: 0},
    {q: "Qu'est-ce que le style évitement ?", o: ["Ignorer ou reporter le conflit", "Affronter directement", "Imposer sa volonté", "Collaborer activement"], c: 0},
    {q: "Qu'est-ce que le style accommodation ?", o: ["Céder aux désirs de l'autre", "Imposer sa volonté", "Éviter le conflit", "Chercher un compromis"], c: 0},
    {q: "Qu'est-ce que le style compromis ?", o: ["Trouver un terrain d'entente acceptable", "Gagner à tout prix", "Céder complètement", "Éviter le problème"], c: 0},
    {q: "Qu'est-ce que le style collaboration ?", o: ["Chercher une solution gagnant-gagnant", "Imposer sa solution", "Éviter le conflit", "Céder aux autres"], c: 0},
    {q: "Quel style est le plus constructif à long terme ?", o: ["Collaboration", "Compétition", "Évitement", "Accommodation"], c: 0},
    {q: "Quand utiliser le style compétition ?", o: ["En situation d'urgence ou décision impopulaire", "Toujours", "Jamais", "Pour les petits problèmes"], c: 0},
    {q: "Quand l'évitement peut-il être approprié ?", o: ["Pour les problèmes mineurs ou temporaires", "Pour tous les conflits", "Jamais", "Toujours"], c: 0},
    {q: "Quel est le risque du style évitement ?", o: ["Le conflit s'aggrave avec le temps", "Résolution trop rapide", "Trop de communication", "Aucun risque"], c: 0},
    {q: "Quand utiliser l'accommodation ?", o: ["Quand la relation est plus importante que l'enjeu", "Toujours", "Jamais", "En cas d'urgence"], c: 0},
    {q: "Quel est l'avantage du compromis ?", o: ["Solution rapide et équitable", "Satisfaction totale de tous", "Aucun avantage", "Victoire complète"], c: 0},
    {q: "Quel est l'inconvénient du compromis ?", o: ["Personne n'est pleinement satisfait", "Trop de temps perdu", "Trop coûteux", "Aucun inconvénient"], c: 0},
    {q: "Pourquoi la collaboration est-elle idéale ?", o: ["Elle satisfait tous les besoins", "Elle est rapide", "Elle évite la discussion", "Elle impose une solution"], c: 0},
    {q: "Quel est l'inconvénient de la collaboration ?", o: ["Elle prend du temps et de l'énergie", "Elle crée des conflits", "Elle est inefficace", "Aucun inconvénient"], c: 0},
    {q: "Peut-on changer de style selon la situation ?", o: ["Oui, c'est recommandé", "Non, il faut un seul style", "Jamais", "C'est impossible"], c: 0},
    {q: "Le style compétition est-il toujours mauvais ?", o: ["Non, il est utile dans certaines situations", "Oui, toujours mauvais", "Il n'existe pas", "Oui, à éviter absolument"], c: 0},
    {q: "Quel style privilégier pour les enjeux importants ?", o: ["Collaboration", "Évitement", "Accommodation", "Compétition pure"], c: 0},
    {q: "Les 5 styles sont-ils exclusifs ?", o: ["Non, on peut les combiner", "Oui, un seul à la fois", "Ils sont identiques", "Ils n'existent pas"], c: 0},

    // SECTION 7: Gestion et prévention (30 questions)
    {q: "Qu'est-ce qu'une communication claire ?", o: ["Un message précis et compréhensible", "Un message vague", "Un silence", "Un cri"], c: 0},
    {q: "Pourquoi la confiance est-elle essentielle ?", o: ["Elle réduit les tensions et favorise la coopération", "Elle crée des conflits", "Elle n'est pas importante", "Elle ralentit le travail"], c: 0},
    {q: "À quoi servent les règles partagées ?", o: ["À structurer les interactions", "À créer la confusion", "À limiter la liberté", "Elles sont inutiles"], c: 0},
    {q: "Qu'est-ce que la participation équilibrée ?", o: ["Chacun contribue de manière égale", "Une personne domine", "Personne ne participe", "Contribution aléatoire"], c: 0},
    {q: "Comment favoriser la participation ?", o: ["En donnant la parole à tous", "En imposant le silence", "En ignorant certains", "En critiquant les idées"], c: 0},
    {q: "Qu'améliore une bonne gestion des conflits ?", o: ["Les relations de travail", "Le stress", "L'absentéisme", "Les tensions"], c: 0},
    {q: "Un conflit bien géré réduit-il le stress ?", o: ["Oui, considérablement", "Non, il l'augmente", "Aucun effet", "Parfois"], c: 0},
    {q: "Quel impact sur l'absentéisme ?", o: ["Il diminue avec une bonne gestion", "Il augmente", "Aucun impact", "Il double"], c: 0},
    {q: "La motivation est-elle renforcée ?", o: ["Oui, par la résolution constructive", "Non, elle baisse", "Elle reste identique", "Elle disparaît"], c: 0},
    {q: "Qu'est-ce que la prise de décision collective ?", o: ["Décisions prises en groupe", "Décision d'une seule personne", "Absence de décision", "Décision aléatoire"], c: 0},
    {q: "Les conflits facilitent-ils les décisions collectives ?", o: ["Oui, s'ils sont bien gérés", "Non, jamais", "Toujours négatif", "Impossible"], c: 0},
    {q: "Qu'est-ce que la créativité de groupe ?", o: ["Capacité à innover ensemble", "Copier les autres", "Absence d'idées", "Routine"], c: 0},
    {q: "Les conflits peuvent-ils stimuler la créativité ?", o: ["Oui, par la diversité des points de vue", "Non, ils la bloquent", "Jamais", "Impossible"], c: 0},
    {q: "Qu'est-ce que la performance d'équipe ?", o: ["L'efficacité collective dans l'atteinte des objectifs", "Le travail individuel", "L'échec", "La lenteur"], c: 0},
    {q: "Une dynamique positive améliore-t-elle la performance ?", o: ["Oui, significativement", "Non, aucun effet", "Elle la diminue", "Parfois"], c: 0},
    {q: "Qu'est-ce que la cohésion d'équipe ?", o: ["Le degré d'unité et de solidarité", "La division", "Le conflit permanent", "L'individualisme"], c: 0},
    {q: "Comment la cohésion influence-t-elle les résultats ?", o: ["Elle améliore la collaboration et les résultats", "Elle les détériore", "Aucun effet", "Elle crée des problèmes"], c: 0},
    {q: "Quel est le rôle du manager dans la dynamique ?", o: ["Faciliter les interactions et gérer les conflits", "Créer des tensions", "Ignorer le groupe", "Dominer complètement"], c: 0},
    {q: "La formation aide-t-elle à gérer les conflits ?", o: ["Oui, elle développe les compétences", "Non, elle est inutile", "Elle aggrave les choses", "Jamais"], c: 0},
    {q: "Qu'est-ce qu'un feedback constructif ?", o: ["Une critique bienveillante pour progresser", "Une attaque personnelle", "Un silence", "Une ignorance"], c: 0},
    {q: "Le feedback améliore-t-il la dynamique ?", o: ["Oui, en clarifiant les attentes", "Non, il crée des conflits", "Il est nuisible", "Aucun effet"], c: 0},
    {q: "Qu'est-ce que l'intelligence émotionnelle ?", o: ["Comprendre et gérer ses émotions et celles des autres", "L'intelligence académique", "L'absence d'émotions", "La logique pure"], c: 0},
    {q: "L'intelligence émotionnelle aide-t-elle en groupe ?", o: ["Oui, pour les relations et conflits", "Non, elle est inutile", "Elle crée des problèmes", "Jamais"], c: 0},
    {q: "Qu'est-ce que l'empathie ?", o: ["Se mettre à la place de l'autre", "L'indifférence", "La critique", "Le jugement"], c: 0},
    {q: "L'empathie réduit-elle les conflits ?", o: ["Oui, en favorisant la compréhension", "Non, elle les aggrave", "Elle est inutile", "Jamais"], c: 0},
    {q: "Qu'est-ce que la diversité en groupe ?", o: ["Variété de perspectives et compétences", "Uniformité totale", "Absence de différences", "Conflit permanent"], c: 0},
    {q: "La diversité est-elle bénéfique ?", o: ["Oui, pour l'innovation et créativité", "Non, elle crée des conflits", "Elle est négative", "Toujours problématique"], c: 0},
    {q: "Comment gérer la diversité ?", o: ["Par l'inclusion et le respect", "Par l'exclusion", "Par l'uniformisation", "Par l'ignorance"], c: 0},
    {q: "Qu'est-ce qu'une culture organisationnelle positive ?", o: ["Valeurs et normes favorisant le bien-être", "Un environnement toxique", "L'absence de règles", "Le chaos"], c: 0},
    {q: "La culture influence-t-elle la dynamique ?", o: ["Oui, profondément", "Non, aucun effet", "Rarement", "Jamais"], c: 0},
    {q: "En conclusion, que faut-il pour une équipe performante ?", o: ["Dynamique positive et gestion constructive des conflits", "Absence de conflits", "Domination d'un leader", "Individualisme"], c: 0}
];